version: '3.8'
services:
  bookworm:
    build: .
    image: nc:flask-app
    volumes:
      - .:/var/www/flask-app
    ports:
      - 5000:5000
    command: bash -c "cd /var/www/flask-app && source environment && flask run --host=0.0.0.0"
